// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rneamwxblioxlhisxaxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZWFtd3hibGlveGxoaXN4YXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODUwMzgsImV4cCI6MjA2NTY2MTAzOH0.jDpfXOhUlPN-z8hCnkIchSH9I-ieUTFf_8jyBTzpNms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);